DevInterview.Web/Areas/ControlPanel/Controllers/AdminController.cs
using System.Linq;
using System.Web.Mvc;
using DevInterview.Bal.Managers.Business.Interfaces;
using DevInterview.Bal.SearchEngine.Base;
using DevInterview.Common.Configuration;
using DevInterview.Common.Utilities.Extensions;
using DevInterview.Dal.Entities.Business;
using DevInterview.Dal.Entities.NotBusiness;
using DevInterview.Web.Controllers.Base;

namespace DevInterview.Web.Areas.ControlPanel.Controllers
{
    [Authorize]
    public class AdminController : AppBaseController
    {
        #region Fields

        private readonly IPostManager postManager;

        private readonly ILuceneSearchEngine searchEngine;

        #endregion


        #region Constructors and Destructors

        public AdminController(IPostManager postManager, ILuceneSearchEngine searchEngine)
        {
            this.postManager = postManager;
            this.searchEngine = searchEngine;
        }

        #endregion


        #region Public Methods and Operators

        public ViewResult Index() => View();

        public void RefreshIndex()
        {
            SearchResult<Post> posts = postManager.GetAll();
            searchEngine.ClearIndex();
            searchEngine.AddPostToIndex(posts.Data);
        }

        public JsonResult SimilarPosts(string query)
        {
            if (query.IsNullOrEmpty())
            {
                return new JsonResult();
            }

            return new JsonResult
            {
                Data = postManager.SearchSimilar(query, AppCfgReader.SimilarPostsSize).Data.Select(p => p.Title),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        #endregion
    }
}

DevInterview.Web/Areas/ControlPanel/Controllers/WebApi/PostsController.cs
using System;
using System.Data.Entity.Core;
using System.Linq;
using System.Web.Http;
using AutoMapper;
using DevInterview.Bal.Managers.Business.Interfaces;
using DevInterview.Bal.SearchEngine.Base;
using DevInterview.Common.Exceptions;
using DevInterview.Common.Exceptions.Presentation;
using DevInterview.Common.Utilities.Helpers;
using DevInterview.Dal.Entities.Business;
using DevInterview.Dal.Entities.NotBusiness;
using DevInterview.Web.Controllers.Base;
using DevInterview.Web.Models;

namespace DevInterview.Web.Areas.ControlPanel.Controllers.WebApi
{
    public class PostsController : WebApiBaseController
    {
        #region Fields

        private readonly IPostManager postManager;

        private readonly ILuceneSearchEngine searchEngine;

        private readonly IUrlizer urlizer;

        #endregion


        #region Constructors and Destructors

        public PostsController(IPostManager postManager, IUrlizer urlizer, ILuceneSearchEngine searchEngine)
        {
            this.postManager = postManager;
            this.urlizer = urlizer;
            this.searchEngine = searchEngine;
        }

        #endregion


        #region Public Methods and Operators

        [HttpDelete]
        public void Delete(int id)
        {
            if (id <= 0)
            {
                var inner = new ArgumentException("ID of Post should be positive.", nameof(id));

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not delete Post.",
                                                    TypeOfException = inner.GetType(),
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException
                                                },
                                                inner);
            }

            postManager.Delete(id);
        }

        [HttpGet]
        public PostModel Get(int id)
        {
            if (id <= 0)
            {
                var inner = new ArgumentException("ID of Post should be positive.", "model");

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not get Post by ID.",
                                                    TypeOfException = inner.GetType(),
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException
                                                },
                                                inner);
            }

            Post post = postManager.Get(id);

            if (post == null)
            {
                var inner = new ObjectNotFoundException($"Post with ID {id} was not found.");

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not get Post from storage.",
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException,
                                                    TypeOfException = inner.GetType()
                                                },
                                                inner);
            }

            var model = Mapper.Map<PostModel>(post);

            return model;
        }

        [HttpGet]
        public SearchResult<PostModel> Get([FromUri] SearchParameters parameters)
        {
            SearchResult<Post> posts = postManager.Search(parameters);

            if (posts == null || posts.TotalRecords == 0 || posts.Data == null)
            {
                return new SearchResult<PostModel>();
            }

            var results = new SearchResult<PostModel>
            {
                TotalRecords = posts.TotalRecords,
                Records = posts.Records,
                Data = posts.Data.Select(Mapper.Map<PostModel>).OrderByDescending(p => p.Created)
            };

            return results;
        }

        [HttpPost]
        public PostModel Post(PostModel model)
        {
            if (model == null)
            {
                var inner = new ArgumentNullException(nameof(model), "Model can not be null.");

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not create Post.",
                                                    TypeOfException = inner.GetType(),
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException
                                                },
                                                inner);
            }

            var post = new Post();
            Mapper.Map(model, post);
            post.UrlSlug = urlizer.GetFriendlyUrl(post.Title);

            foreach (Tag tag in post.Tags)
            {
                tag.UrlSlug = urlizer.GetFriendlyUrl(tag.Title);
            }

            Post result = postManager.Create(post);
            model.Id = result.Id;

            return model;
        }

        [HttpPut]
        public PostModel Put(PostModel model)
        {
            if (model == null || model.Id <= 0)
            {
                ArgumentException inner = model == null
                                              ? new ArgumentNullException(nameof(model), "Model can not be null.")
                                              : new ArgumentException("ID of model should be positive.", nameof(model));

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not update Post.",
                                                    TypeOfException = inner.GetType(),
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException
                                                },
                                                inner);
            }

            Post post = postManager.Get(model.Id);

            if (post == null)
            {
                var inner = new ObjectNotFoundException($"Post with ID {model.Id} was not found in storage.");

                throw new PresentationException(
                                                new ExceptionMessage
                                                {
                                                    FailedOperationDescription = "Can not update Post.",
                                                    TypeOfException = inner.GetType(),
                                                    PossibleReason = ExceptionHelper.ReferenceToInnerException
                                                },
                                                inner);
            }

            Mapper.Map(model, post);
            post.UrlSlug = urlizer.GetFriendlyUrl(post.Title);

            foreach (Tag tag in post.Tags)
            {
                tag.UrlSlug = urlizer.GetFriendlyUrl(tag.Title);
            }

            post = postManager.Update(post);

            searchEngine.AddPostToIndex(post);

            return model;
        }

        #endregion
    }
}

DevInterview.Web/Controllers/SidebarController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DevInterview.Bal.Managers.Business.Interfaces;
using DevInterview.Bal.Providers.Interfaces;
using DevInterview.Dal.Entities.Business;
using DevInterview.Dal.Entities.NotBusiness;
using DevInterview.Web.Controllers.Base;
using DevInterview.Web.Models;

namespace DevInterview.Web.Controllers
{
    public class SidebarController : AppBaseController
    {
        #region Fields

        private readonly ICategoryManager categoryManager;

        private readonly IPostManager postManager;

        private readonly IStatisticsProvider statisticsProvider;

        private readonly ITagManager tagManager;

        #endregion


        #region Constructors and Destructors

        public SidebarController(ICategoryManager categoryManager, ITagManager tagManager, IPostManager postManager, IStatisticsProvider statisticsProvider)
        {
            this.categoryManager = categoryManager;
            this.tagManager = tagManager;
            this.postManager = postManager;
            this.statisticsProvider = statisticsProvider;
        }

        #endregion


        #region Public Methods and Operators

        public ActionResult About()
        {
            var model = new StatisticsModel
            {
                VotesCount = statisticsProvider.VotesCount(),
                CategoriesCount = statisticsProvider.CategoriesCount(),
                PostsCount = statisticsProvider.PostsCount(),
                DaysSinceStart = statisticsProvider.DaysSinceStart(),
                TagsCount = statisticsProvider.TagsCount()
            };

            return View(model);
        }

        public ActionResult Categories()
        {
            SearchResult<Category> categories = categoryManager.GetAll();

            if (categories == null || categories.TotalRecords == 0 || categories.Data == null)
            {
                return View(new List<CategoryModel>());
            }

            List<CategoryModel> models = categories.Data.Select(Mapper.Map<CategoryModel>).ToList();

            foreach (CategoryModel cat in models)
            {
                cat.PostsCount = postManager.GetPostsCountByCategory(cat.Id);
            }

            return View(models);
        }

        public ActionResult Tags()
        {
            SearchResult<Tag> tags = tagManager.GetAll();
            if (tags == null || tags.TotalRecords == 0 || tags.Data == null)
            {
                return View(new List<TagModel>());
            }

            List<TagModel> models = tags.Data.Select(Mapper.Map<TagModel>).ToList();

            foreach (TagModel tag in models)
            {
                tag.PostsCount = postManager.GetTaggedPostsCountByTag(tag.Id);
            }

            return View(models.Where(t => t.PostsCount > 0).ToList());
        }

        #endregion
    }
}

DevInterview.Web/Views/Shared/_Layout.cshtml
@using DevInterview.Common.Configuration
@using DevInterview.Web.Infrastructure.RazorExtensions
<!DOCTYPE html>
<html lang="en">
<head prefix="og: http://ogp.me/ns#">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="@ViewBag.MetaDescription">
	<meta name="robots" content="all"/>
	<meta name="msvalidate.01" content="3054E54266B5F0A7601851185E75FEDB"/>
	<meta property="og:site_name" content="@AppCfgReader.DomainName"/>
	<meta property="og:title" content="@ViewBag.MetaTitle"/>
	<meta property="og:url" content="@ViewBag.CanonicalUrl"/>
	<meta property="og:description" content="@ViewBag.MetaDescription"/>
	<meta property="og:image" content="@string.Format("http://{0}/Images/site-preview.png", AppCfgReader.DomainName)"/>
	@if (IsSectionDefined("metatags"))
	{
		@RenderSection("metatags", false)
	}
	else
	{
		<meta property="og:type" content="website"/>
	}
	<link rel="canonical" href="@ViewBag.CanonicalUrl">
	<title>@ViewBag.MetaTitle</title>
	<link href="http://fonts.googleapis.com/css?family=Ubuntu+Mono" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
	<link href="http://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
	@Styles.Render("~/bundles/css")
	@RenderSection("styles", false)
	@if (!Request.IsLocal)
	{
	    <script>
    	    (function(i, s, o, g, r, a, m) {
    	        i['GoogleAnalyticsObject'] = r;
    	        i[r] = i[r] ||
    	            function() {
    	                (i[r].q = i[r].q || []).push(arguments);
    	            }, i[r].l = 1 * new Date();
    	        a = s.createElement(o),
    	            m = s.getElementsByTagName(o)[0];
    	        a.async = 1;
    	        a.src = g;
    	        m.parentNode.insertBefore(a, m);
    	    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    	    ga('create', 'UA-69101813-2', 'auto');
    	    ga('require', 'linkid');
    	    ga('send', 'pageview');
    	</script>
	}
</head>
<body itemscope itemtype="http://schema.org/WebPage">
<meta itemprop="name" content="@ViewBag.MetaTitle"/>
<meta itemprop="description" content="@ViewBag.MetaDescription"/>
<div id="fb-root"></div>
<script>
	(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) {
			return;
		}
		js = d.createElement(s);
		js.id = id;
		js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script>
<header>
	<nav class="navbar navbar-default navbar-fixed-top" itemscope itemtype="http://schema.org/SiteNavigationElement">
		<div class="container">
			<div class="navbar-logo">
				<a href="/" itemprop="url">Dev.Interview</a>
			</div>
			<div class="navbar-menu">
				<div>
					<a href="@Url.RouteUrl("TopRated")" class="btn btn-link" itemprop="url" title="Top Rated">
						<span class="glyphicon glyphicon-king" aria-hidden="true"></span>&nbsp;<span class="@Html.ActivePage("TopRated", "Post")" itemprop="name">Top Rated</span>
					</a>
				</div>
				<div>
					<a href="@Url.RouteUrl("MostViewed")" class="btn btn-link" itemprop="url" title="Most Viewed">
						<span class="glyphicon glyphicon-fire" aria-hidden="true"></span>&nbsp;<span class="@Html.ActivePage("MostViewed", "Post")" itemprop="name">Most Viewed</span>
					</a>
				</div>
				<div>
					<a href="@Url.RouteUrl("Rss")" class="btn btn-link" itemprop="url" title="RSS">
						<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;<span itemprop="name">RSS</span>
					</a>
				</div>
				<div>
					<a href="@Url.RouteUrl("About")" class="btn btn-link" itemprop="url" title="About">
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;<span class="@Html.ActivePage("About", "Home")" itemprop="name">About</span>
					</a>
				</div>
				<div>
					<a href="@Url.RouteUrl("Search")" class="btn btn-link btn-search" itemprop="url" title="Search">
						<span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;<span class="@Html.ActivePage("Search", "Post")" itemprop="name">Search</span>
					</a>
				</div>
				@if (Request.IsAuthenticated)
				{
					<div>
						@Html.ActionLink("Control Panel", "Index", "Admin", new
						{
							Area = "ControlPanel"
						}, new
						{
							@class = "btn btn-link " + Html.ActivePage("Index", "Admin")
						})
					</div>
					<div>
						@Html.ActionLink("Log out", "Logoff", "Account", new
						{
							area = ""
						}, new
						{
							@class = "btn btn-link " + Html.ActivePage("Logoff", "Account")
						})
					</div>
				}
			</div>
		</div>
	</nav>
</header>
<div class="container">
	<div class="row">
		<main class="body-content widget col-lg-9">
			@RenderBody()
		</main>
		<aside class="sidebar col-lg-3" itemscope itemtype="http://schema.org/WPSideBar">
			@Html.Partial("_Sidebar")
		</aside>
	</div>
</div>
<footer class="footer-container hidden-xs hidden-sm hidden-md">
	<div class="footer-text">© @DateTime.Now.Year @AppCfgReader.DomainName — prepare yourself for the next interview</div>
</footer>
@Scripts.Render("~/bundles/browser-selector")
@RenderSection("scripts", false)
<script>
	(function() {
		window.VanillaApp = window.VanillaApp || {};

		window.VanillaApp.voteUp = function(id) {
			var xhttp = new XMLHttpRequest();
			xhttp.onreadystatechange = function() {
				if (xhttp.readyState == 4 && xhttp.status == 200 && xhttp.responseText == "\"ok\"") {
					var votes = document.getElementById('spnVotesDiff' + id);
					votes.innerHTML = parseInt(votes.innerHTML) + 1;
					votes.title = votes.innerHTML;
					votes.className = votes.className + " blue";

					var votesUp = document.getElementById('spnVoteUp' + id);
					votesUp.title = parseInt(votes.title) + 1;
				}
			};
			xhttp.open('GET', '/Post/VotePost/' + id + '?voteUp=true', true);
			xhttp.send();
		};

		window.VanillaApp.voteDown = function(id) {
			var xhttp = new XMLHttpRequest();
			xhttp.onreadystatechange = function() {
				if (xhttp.readyState == 4 && xhttp.status == 200 && xhttp.responseText == "\"ok\"") {
					var votes = document.getElementById('spnVotesDiff' + id);
					votes.innerHTML = parseInt(votes.innerHTML) - 1;
					votes.title = votes.innerHTML;

					var votesDown = document.getElementById('spnVoteDown' + id);
					votesDown.title = parseInt(votes.title) - 1;
				}
			};
			xhttp.open('GET', '/Post/VotePost/' + id + '?voteUp=false', true);
			xhttp.send();
		};
	})();
</script>
<script type="text/javascript">
	/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	var disqus_shortname = 'developerinterview'; // required: replace example with your forum shortname

	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function() {
		var s = document.createElement('script');
		s.async = true;
		s.type = 'text/javascript';
		s.src = '//' + disqus_shortname + '.disqus.com/count.js';
		(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
	}());
</script>
</body>
</html>

DevInterview.Web/Views/Shared/_Post.cshtml
@model PostModel

<article class="post-wrapper" @(!Model.IsFullPost ? "itemprop=blogPost" : "") itemscope itemtype="http://schema.org/BlogPosting">
	<meta itemprop="name" content="@ViewBag.MetaTitle"/>
	<meta itemprop="description" content="@ViewBag.MetaDescription"/>
	<header class="post-header">
		@if (Model.IsFullPost)
		{
			<h1 itemprop="headline">
				@Model.Title
				@if (Request.IsAuthenticated)
				{
					<a href="@Url.Action("Index", "Admin", new
					         {
						         Area = "ControlPanel"
					         })/EditPost/@Model.Id" class="btn btn-default btn-xs">
						Edit
					</a>
				}
			</h1>
		}
		else
		{
			<h2 itemprop="headline">
				@Html.RouteLink(Model.Title, "Post", new
				{
					id = Model.Id,
					category = Model.Category.UrlSlug,
					url = Model.UrlSlug
				}, null)
			</h2>
		}
		@{ Html.RenderPartial("_PostInfo", Model); }
	</header>
    <div class="post-body" itemprop="articleBody">
        @Html.Raw(Model.BodyStart)
        @if (Model.IsFullPost)
        {
            @Html.Raw(Model.BodyEnd)
        }
    </div>
	<footer class="post-footer clearfix">
		@{ Html.RenderPartial("_PostFooter", Model); }
	</footer>
</article>
<div class="post-separator"></div>

DevInterview.Web/Views/Shared/_PostFooter.cshtml
@using DevInterview.Web.Infrastructure.RazorExtensions
@model PostModel
@{
	string pageUrl = Url.AbsoluteRouteUrl("Post", new
	{
		id = Model.Id,
		category = Model.Category.UrlSlug,
		url = Model.UrlSlug
	});
	string date = Model.Created.ToString("yyyy-MM-dd");
}

<div class="footer-post-info">
	<div class="post-tags">
		@foreach (TagModel tag in Model.Tags)
		{
			@Html.RouteLink(tag.Title, "Tag", new
			{
				tag = tag.UrlSlug
			}, new
			{
				@class = "btn btn-default btn-xs"
			})
		}
	</div>
	<div class="post-date">
		<span>
			<time itemprop="datePublished" datetime="@date">@Model.Created.Date.ToShortDateString()</time> at @Html.RouteLink(Model.Category.Title, "Category", new
			                                                                                                  {
				                                                                                                  category = Model.Category.UrlSlug
			                                                                                                  })</span>
	</div>
</div>
@if (Model.IsFullPost)
{
	<div class="social-buttons">
		<div class="fb-like" data-href="@pageUrl" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
		<span class="post-share-separator">ѳ</span>
		<a href="http://twitter.com/intent/tweet?url=@pageUrl&text=@Uri.EscapeUriString(Model.Title)" target="_blank">
			<img alt="Share on Twitter" src="~/Images/tweet-button.png"/>
		</a>
		<span class="post-share-separator">ѳ</span>
		<a href="https://plus.google.com/share?url=@pageUrl" target="_blank">
			<img alt="Share on Google+" src="~/Images/g-button.png"/>
		</a>
	</div>
}

DevInterview.Web/Views/Shared/_PostInfo.cshtml
@using DevInterview.Web.Infrastructure.RazorExtensions
@model PostModel
@{
	int rating = Model.Rating.VotesDifference;
	string ratingBadgeClass = rating > 0 ? "blue" : "gray";
	string date = Model.Created.ToString("yyyy-MM-dd");
}

<div class="post-info">
	<span class="post-info-section">
		<span class="glyphicon glyphicon-arrow-up" title="@Model.Rating.VotesUp" onclick="VanillaApp.voteUp(@Model.Id)" id="@("spnVoteUp" + Model.Id)"></span>
		<span class="badge @ratingBadgeClass" title="@Model.Rating.VotesDifference" id="@("spnVotesDiff" + Model.Id)">@rating</span>
		<span class="glyphicon glyphicon-arrow-down" title="@Model.Rating.VotesDown" onclick="VanillaApp.voteDown(@Model.Id)" id="@("spnVoteDown" + Model.Id)"></span>
	</span>
	<span class="post-info-separator">ѳ</span>
	<span class="post-info-section">
		<span class="glyphicon glyphicon-eye-open"></span><span class="badge no-margin-right">@Model.Views</span>
	</span>
	<span class="post-info-separator">ѳ</span>
	<span class="post-info-section">
		<a href="@Url.RouteUrl("Post", new
		         {
			         id = Model.Id,
			         category = Model.Category.UrlSlug,
			         url = Model.UrlSlug
		         })#comments" itemprop="discussionUrl">
			comments
			<span class="badge comments-counter disqus-comment-count" data-disqus-url="@Url.AbsoluteRouteUrl("Post", new
			                                                                           {
				                                                                           id = Model.Id,
				                                                                           category = Model.Category.UrlSlug,
				                                                                           url = Model.UrlSlug
			                                                                           })">
				0
			</span>
		</a>
	</span>
</div>

DevInterview.Web/Views/Shared/_Sidebar.cshtml
@{ Html.RenderAction("Categories", "Sidebar", new
    {
        area = ""
    }); }
@{ Html.RenderAction("Tags", "Sidebar", new
    {
        area = ""
    }); }
@{ Html.RenderAction("About", "Sidebar", new
    {
        area = ""
    }); }